config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/conwisol'

  get 'static_pages/liakorConstruction'

  get 'static_pages/liakorColloid'

  get 'static_pages/liakorHousehold'

  resources :products
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contacts'

  root 'static_pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :category)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contacts
  end

  def conwisol
  	@products = Product.all.where('category' => [1])
  end

  def liakorConstruction
  	@products = Product.all.where('category' => [2])
  end

  def liakorColloid
  	@products = Product.all.where('category' => [3])
  end

  def liakorHousehold
  	@products = Product.all.where('category' => [4])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>LIAKOR. The Chemical Industry</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<div id="container">
		<header class="clearfix">
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu">
							<span class="sr-only">Toggle navigation</span>
        						<span class="icon-bar"></span>
        						<span class="icon-bar"></span>
        						<span class="icon-bar"></span>
							</button> 

							<%= link_to "IAKOR", root_path, :class => 'navbar-brand'%>
					</div>
					<div class="collapse navbar-collapse" id="menu">
						<ul class="nav navbar-nav navbar-right">
							<li>
								<%= active_link_to 'Головна', root_path, :active => {:when => :self_only}  %>
							</li>
							<li>
								<%= active_link_to 'Про нас', static_pages_about_path %>
							</li>
							<li>
								<%= active_link_to 'Conwisol', static_pages_conwisol_path %>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Liakor 
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<li>
										<%= active_link_to 'Будівельна хімія', static_pages_liakorConstruction_path %>
									</li>
									<li>
										<%= active_link_to 'Колоїдна хімія', static_pages_liakorColloid_path %>
									</li>
									<li>
										<%= active_link_to 'Побутова хімія', static_pages_liakorHousehold_path %>
									</li>
								</ul>
							</li>
							<li>
								<%= active_link_to 'Контакти', static_pages_contacts_path %>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			</header>
		
<%= yield %>
	<div class="push"></div>
	</div>

	<div class="container-fluid footer darkGrey">
			<div class="container">
				<div class="col-sm-3 col-xs-6">
					<h1 id="brand"><span class="orangeTxt">L</span>IKOR</h1>
					<span>Усі права зареєстровані ©</span><br>
					<span>2000-2016</span>
				</div>
				<div class="col-sm-7 col-xs-6">
					<nav class="navbar">
						<ul class="nav navbar-nav">
								<li>
								<%= active_link_to 'Головна', root_path, :active => {:when => :self_only}  %>
							</li>
							<li>
								<%= active_link_to 'Про нас', static_pages_about_path %>
							</li>
								<li>
									<a href="#">Conwisol</a>
								</li>
								<li>
									<a href="#">Liakor</a>
								</li>
								<li>
									<%= active_link_to 'Контакти', static_pages_contacts_path %>
								</li>
							</ul>
					</nav>
					<p class="address" style="">
							02160, Україна, м.Київ,
							<br>
							вул. Каунаська, 13, корп. А, оф.2
							<br>
							тел. +380 44 384-42-70
						</p>
				</div>
			</div>
		</div>


</body>
</html>

app/views/products/_form.html.erb
  <div class="col-sm-6">
  <%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :category %><br>
      <%= f.number_field :category, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", class: "btn" %>
    </div>
  </div>
  <div class="col-sm-6">
    <p><b>Category Key</b></p>
    <ul>
      <li>1 - Conwisol</li>
      <li>2 - Liakor - Будівельна хімія</li>
      <li>3 - Liakor - Колоїдна хімія</li>
      <li>4 - Liakor - Побутова хімія</li>
    </ul>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-4">
	<%= image_tag(product.image_url, class: "img-responsive") %>
	<h4><%= product.name %></h4>
	<p class="text"><%= product.description %></p>

	<!-- <span style="color: #ccc"><%= product.category %></span> -->
	<%= link_to 'Змінити', edit_product_path(product) %>
	<%= link_to 'Знищити', product, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="row"><br/>
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>

<br>
</div>
  <%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<div class="container-fluid darkGrey pagetitle">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1 class="title">Створити новий продукт</h1>
			</div>
			<div class="col-sm-6 breadcrmbs">
		  		<a href="#">Головна /</a>
		  		<a href="#">Продукт /</a>
		  		<a href="#" class="active">Створити</a>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<br/>
	<%= render 'form' %>

<div class="col-sm-12">
	<%= link_to 'Back', products_path %>
</div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-4">
	<%= image_tag(@product.image_url, class: "img-responsive") %>
</div>
<div class="col-sm-8">
	<h4><%= @product.name %></h4>
	<p class="text"><%= @product.description %></p>
	<%= link_to 'Edit', edit_product_path(@product) %> |
	<%= link_to 'Back', products_path %>
</div>

app/views/static_pages/about.html.erb
<div class="container-fluid darkGrey pagetitle">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h1 class="title">Про нас</h1>
					</div>
					<div class="col-sm-6 breadcrmbs">
				  		<a href="#">Головна /</a>
				  		<a href="#" class="active">Про нас</a>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<br>
				<div class="col-sm-6">
					<%= image_tag("intro1.jpg", class: "img-responsive") %>
					<h4>ЧОМУ CАМЕ МИ?</h4>
					<p class="text">
						Вітчизняний виробник хімічної продукції фірма ЛІАКОР в своїй діяльності використовує філософію міжнародної програми Responsible Care, що дослівно
						переводиться як "відповідальна турбота " і являє собою міжнародну добровільну ініціативу хімічної промисловості всього світу, спрямовану на неухильне поліпшення показників в галузі охорони навколишнього середовища, здоров'я та безпеки праці.
					</p>
				</div>
				<div class="col-sm-6">
					<%= image_tag("intro.jpg", class: "img-responsive") %>
					<h4>ВСЕ, ЩО ВИ МАЄТЕ ЗНАТИ ПРО НАС</h4>
					<p class="text">
						Раціональне використання і відтворення природних ресурсів, моделювання і розробка власної сировинної бази, застосування світових технологій знайшло втілення в матеріалах, які ми випускаємо під власними торговими марками CONWISOL і LIAKOR.
					</p>
				</div>
			</div>
		</div>
		<br>

app/views/static_pages/contacts.html.erb
<div class="container-fluid darkGrey pagetitle">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h1 class="title">Контакти</h1>
					</div>
					<div class="col-sm-6 breadcrmbs">
				  		<a href="#">Головна /</a>
				  		<a href="#" class="active">Контакти</a>
					</div>
				</div>
			</div>
		</div>
		<div id="map">
			<iframe frameborder="0" style="border:0" width="100%" height="500"
  			src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCVmkStWyMJMRilz0kPQXuPj6JMZDWkUJQ&q=Space+Needle,Seattle+WA" allowfullscreen>
			</iframe>
		</div>
		<div class="container">
			<div class="contact">
				<div class="col-sm-5">
					<h2>Контакти</h2>
					<ul class="information-list">
  						<li><i class="fa fa-map-marker"></i><span>вул. Каунаська, 13, корп. А, оф.2,
  						Україна, м.Київ 02160</span></li>
  						<li><i class="fa fa-phone"></i> <span>+380 44 384-42-70</span></li>
  						<li><i class="fa fa-envelope-o"></i><a href="mailto:liakor@gmail.com">liakor@gmail.com</a></li>
					</ul>
				</div>
				<div class="col-sm-7">
					<h2>Відправте нам Email</h2>
					<form class="contact" style="margin-bottom: 40px;">
						<input type="text" placeholder="Ім'я" class="form-control">
						<input type="email" placeholder="Email" class="form-control">
						<input type="phone" placeholder="Тел" class="form-control">
						<textarea type="text" placeholder="" class="form-control">
						</textarea>

						<input type="submit" value="Відправити" class="btn orangeBg">
					</form>
				</div>
			</div>
		</div>

app/views/static_pages/conwisol.html.erb
<div class="container-fluid darkGrey pagetitle">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h1 class="title">ДОБАВКИ ДО БЕТОНІВ ТА БУДІВЕЛЬНИХ РОЗЧИНІВ CONWISOL</h1>
					</div>
					<div class="col-sm-6 breadcrmbs">
				  		<a href="#">Продукція /</a>
				  		<a href="#" class="active">Conwisol</a>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<br/>
			    <% @products.each do |product| %>
			       <%= render partial: "products/product", locals: {product: product} %>
			    <% end %>
			<br>
			</div>
		</div>
		<br>

app/views/static_pages/index.html.erb
<div class="container-fluid">
	<div class="row" id="slider">
		<h2>Liakor<br>
			<small>Ми працюємо для вас</small></h2>
	</div>
</div>

<div class="container-fluid grey">
			<div class="container">
				<div id="intro" class="row">
					<div class="col-sm-4">
						<%= image_tag("conwisol/4.png", class: "img-responsive") %>
						<h4>Добавки до бетонів та будівельних розчинів <b>Conwisol</b></h4>
						<p>As the general contractor, we first create the highest level of trust and integrity with our clients. We value our role in the success of your project.</p>
					</div>
					<div class="col-sm-4">
						<%= image_tag("intro1.jpg", class: "img-responsive") %>
						<h4>Будівельна хімія <b>Liakor</b></h4>
						<p>Constructor explains how you can enjoy high end flooring trends like textured wood and realistic stones with new laminate flooring.</p>
					</div>
					<div class="col-sm-4">
						<%= image_tag("conwisol/2.png", class: "img-responsive") %>
						<h4>Про компанію</h4>
						<p>Green construction refers to a structure and using process that is environmentally responsible and resource-efficient throughout a building's life-cycle.</p>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid darkGrey about">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<h1>Про нас</h1>
					</div>

				<div class="col-sm-7">
					<p>
						Вітчизняний виробник хімічної продукції фірма ЛІАКОР в своїй діяльності використовує філософію міжнародної програми Responsible Care, що дослівно
						переводиться як "відповідальна турбота " і являє собою міжнародну добровільну ініціативу хімічної промисловості всього світу, спрямовану на неухильне поліпшення показників в галузі охорони навколишнього середовища, здоров'я та безпеки праці.
						<br><br>
						Раціональне використання і відтворення природних ресурсів, моделювання і розробка власної сировинної бази, застосування світових технологій знайшло втілення в матеріалах, які ми випускаємо під власними торговими марками CONWISOL і LIAKOR
					</p>
				</div>
				<div class="col-sm-5">
					<%= image_tag("about.jpg", class: "img-responsive") %>
				</div>
				</div>
			</div>
		</div>
		<div class="map">
			<iframe frameborder="0" style="border:0" width="100%" height="500"
  			src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCVmkStWyMJMRilz0kPQXuPj6JMZDWkUJQ&q=Space+Needle,Seattle+WA" allowfullscreen>
			</iframe>
			<div class="container">
				<div class="row contact">
					<div class="col-sm-7">
					</div>
					<div class="col-sm-5">
						<form id="contact" class="contact">
							<h2>Є питання? Напишіть нам</h2>
							<input type="text" placeholder="Ім'я" class="form-control">
							<input type="email" placeholder="Email" class="form-control">
							<input type="phone" placeholder="Тел" class="form-control">
							<textarea type="text" placeholder="" class="form-control">
							</textarea>

							<input type="submit" value="Відправити" class="btn orangeBg">
						</form>
					</div>
				</div>
			</div>
		</div>

app/views/static_pages/liakorColloid.html.erb
<div class="container-fluid darkGrey pagetitle">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h1 class="title">LIAKOR. КОЛОЇДНА ХІМІЯ</h1>
					</div>
					<div class="col-sm-6 breadcrmbs">
				  		<span>Продукція /</span>
				  		<span class="active">Liakor</span>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<br/>
			    <% @products.each do |product| %>
			       <%= render partial: "products/product", locals: {product: product} %>
			    <% end %>
			<br>
			</div>
		</div>
		<br>

app/views/static_pages/liakorConstruction.html.erb
<div class="container-fluid darkGrey pagetitle">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h1 class="title">LIAKOR. БУДІВЕЛЬНА ХІМІЯ</h1>
					</div>
					<div class="col-sm-6 breadcrmbs">
				  		<span>Продукція /</span>
				  		<span class="active">Liakor</span>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<br/>
			    <% @products.each do |product| %>
			       <%= render partial: "products/product", locals: {product: product} %>
			    <% end %>
			<br>
			</div>
		</div>
		<br>

app/views/static_pages/liakorHousehold.html.erb
<div class="container-fluid darkGrey pagetitle">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h1 class="title">LIAKOR. ПОБУТОВА ХІМІЯ</h1>
					</div>
					<div class="col-sm-6 breadcrmbs">
				  		<span>Продукція /</span>
				  		<span class="active">Liakor</span>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<br/>
			    <% @products.each do |product| %>
			       <%= render partial: "products/product", locals: {product: product} %>
			    <% end %>
			<br>
			</div>
		</div>
		<br>